// <auto-generated />
using System;
using AnyTimerApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnyTimerApi.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191002141635_Initial migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnyTimerApi.Database.Entities.AnyTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<uint>("Amount")
                        .HasColumnName("amount");

                    b.Property<string>("ReceiverId")
                        .HasColumnName("receiver_id");

                    b.Property<string>("RequesterId")
                        .HasColumnName("requester_id");

                    b.HasKey("Id")
                        .HasName("pk_any_timers");

                    b.HasIndex("ReceiverId")
                        .HasName("ix_any_timers_receiver_id");

                    b.HasIndex("RequesterId")
                        .HasName("ix_any_timers_requester_id");

                    b.ToTable("any_timers");
                });

            modelBuilder.Entity("AnyTimerApi.Database.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AnyTimerApi.Database.Entities.AnyTimer", b =>
                {
                    b.HasOne("AnyTimerApi.Database.Entities.User", "Receiver")
                        .WithMany("Received")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("fk_any_timers_users_receiver_id");

                    b.HasOne("AnyTimerApi.Database.Entities.User", "Requester")
                        .WithMany("Sent")
                        .HasForeignKey("RequesterId")
                        .HasConstraintName("fk_any_timers_users_requester_id");
                });
#pragma warning restore 612, 618
        }
    }
}
